name: Automerge

on:
  push:
    branches:
      - dev

env:
  MY_REPO: https://GingerIndustries:${{secrets.GITHUB_TOKEN}}@github.com/Vyxal/Crosshatch.git

  MY_BRANCH: pi-dev

  # replace it with the path to master repo
  MASTER_REPO: https://github.com/Vyxal/Crosshatch.git

  MASTER_BRANCH: dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "bot@example.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push
